import { EngineerProfile, RoleData } from './types';

export const ROLES: RoleData[] = [
  { id: 'senior-cloud', label: 'Senior Cloud Engineer', baseSalary: 160000, scarcityFactor: 1.5 },
  { id: 'devops-lead', label: 'DevOps Lead', baseSalary: 180000, scarcityFactor: 1.8 },
  { id: 'security-eng', label: 'Security Engineer', baseSalary: 170000, scarcityFactor: 1.6 },
  { id: 'platform-eng', label: 'Platform Engineer', baseSalary: 155000, scarcityFactor: 1.4 },
  { id: 'sre', label: 'Site Reliability Engineer', baseSalary: 165000, scarcityFactor: 1.5 },
];

export const MOCK_PROFILES: EngineerProfile[] = [
  // Original 8 Profiles
  {
    id: '1',
    firstName: 'David',
    lastInitial: 'K',
    title: 'EUC & Cloud Transformation Specialist',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Senior infrastructure architect with extensive experience leading large-scale Azure migrations for financial sector clients. Specialises in hybrid identity management and zero-trust security implementations.',
    skills: ['Azure Architecture', 'Identity Management', 'Migration Strategy', 'EUC', 'Virtualization', 'Infrastructure as Code', 'Serverless', 'Networking'],
    tools: ['Terraform', 'Intune', 'Entra ID', 'PowerShell', 'Bicep', 'Citrix', 'VMware', 'Azure Monitor'],
    demandLevel: 'Very High',
    marketScore: 94,
    yearsExperience: 12
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastInitial: 'M',
    title: 'Senior DevOps & Automation Engineer',
    location: 'Wellington',
    status: '2 Weeks',
    summary: 'Platform engineering lead focused on reducing toil through advanced CI/CD pipelines and container orchestration. Proven track record stabilising high-traffic production environments in government sectors.',
    skills: ['Kubernetes', 'CI/CD Pipelines', 'Container Security', 'Cloud Native', 'Observability', 'Linux Systems', 'GitOps', 'Release Engineering'],
    tools: ['ArgoCD', 'Helm', 'Prometheus', 'Grafana', 'Github Actions', 'AWS EKS', 'Python', 'Ansible'],
    demandLevel: 'Critical',
    marketScore: 97,
    yearsExperience: 9
  },
  {
    id: '3',
    firstName: 'James',
    lastInitial: 'P',
    title: 'Cybersecurity & GRC Consultant',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Operational security specialist bridging the gap between compliance frameworks and technical implementation. Deep expertise in incident response and securing cloud workloads against modern threat vectors.',
    skills: ['Cloud Security', 'Threat Hunting', 'GRC', 'Incident Response', 'Network Security', 'Penetration Testing', 'SIEM', 'Compliance'],
    tools: ['Sentinel', 'Splunk', 'CrowdStrike', 'NIST Framework', 'Kali Linux', 'Palo Alto', 'Tenable', 'Wireshark'],
    demandLevel: 'High',
    marketScore: 91,
    yearsExperience: 15
  },
  {
    id: '4',
    firstName: 'Michael',
    lastInitial: 'T',
    title: 'Senior Site Reliability Engineer',
    location: 'Christchurch',
    status: '4 Weeks',
    summary: 'Reliability-focused engineer obsessed with uptime, SLO management, and chaotic failure testing. Experienced in scaling database infrastructure and optimizing cost across multi-cloud environments.',
    skills: ['Site Reliability', 'Database Tuning', 'Chaos Engineering', 'Capacity Planning', 'Multi-Cloud', 'Performance Tuning', 'Incident Management', 'Coding'],
    tools: ['Datadog', 'PagerDuty', 'PostgreSQL', 'Go', 'AWS Lambda', 'Redis', 'New Relic', 'Jira Service Mgmt'],
    demandLevel: 'Very High',
    marketScore: 95,
    yearsExperience: 8
  },
  {
    id: '5',
    firstName: 'Emma',
    lastInitial: 'R',
    title: 'Azure Platform Architect',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Enterprise architect focused on landing zone design and governance at scale. Helps organisations mature their cloud operating models while maintaining strict security controls.',
    skills: ['Azure Governance', 'Landing Zones', 'Cloud Architecture', 'Policy Management', 'Cost Optimization', 'Stakeholder Mgmt', 'Hybrid Cloud', 'Storage'],
    tools: ['Azure Policy', 'CAF', 'Blueprints', 'Cost Management', 'Azure Arc', 'Logic Apps', 'Service Bus', 'Key Vault'],
    demandLevel: 'High',
    marketScore: 89,
    yearsExperience: 14
  },
  {
    id: '6',
    firstName: 'Jason',
    lastInitial: 'L',
    title: 'Cloud Network Security Engineer',
    location: 'Wellington',
    status: '2 Weeks',
    summary: 'Network infrastructure specialist transitioning legacy WANs to SD-WAN and SASE architectures. Deeply technical background in routing, switching, and firewall configuration.',
    skills: ['Network Architecture', 'SD-WAN', 'Firewall Mgmt', 'VPN', 'Cloud Networking', 'Routing', 'Switching', 'SASE'],
    tools: ['Fortinet', 'Cisco Meraki', 'Zscaler', 'Azure Virtual WAN', 'AWS Transit Gateway', 'BGP', 'OSPF', 'WireGuard'],
    demandLevel: 'High',
    marketScore: 88,
    yearsExperience: 10
  },
  {
    id: '7',
    firstName: 'Robert',
    lastInitial: 'H',
    title: 'Kubernetes Platform Engineer',
    location: 'Hamilton',
    status: 'Immediate',
    summary: 'Containerisation expert capable of building production-grade K8s clusters from bare metal or managed services. Focuses on developer experience and secure supply chain practices.',
    skills: ['Kubernetes', 'Container Runtime', 'Service Mesh', 'DevSecOps', 'Build Systems', 'Registry Mgmt', 'Secret Mgmt', 'API Gateway'],
    tools: ['Istio', 'Rancher', 'Harbor', 'Vault', 'Jenkins', 'Docker', 'Kong', 'OpenShift'],
    demandLevel: 'Very High',
    marketScore: 93,
    yearsExperience: 7
  },
  {
    id: '8',
    firstName: 'Anita',
    lastInitial: 'W',
    title: 'M365 & Modern Work Engineer',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'End-user computing specialist transforming employee experience through Modern Work implementations. Expert in securing remote workforces and automating device provisioning.',
    skills: ['Modern Workplace', 'Endpoint Mgmt', 'Collaboration', 'Identity', 'Security Baselines', 'OS Deployment', 'Messaging', 'Power Platform'],
    tools: ['MS Endpoint Mgr', 'SharePoint', 'Teams', 'Exchange Online', 'Autopilot', 'Defender', 'Power Automate', 'SCCM'],
    demandLevel: 'High',
    marketScore: 86,
    yearsExperience: 11
  },
  // AWS & Cloud Native
  {
    id: '9',
    firstName: 'Lucas',
    lastInitial: 'B',
    title: 'Senior AWS Solutions Architect',
    location: 'Auckland',
    status: '2 Weeks',
    summary: 'Certified professional architecting highly available, fault-tolerant systems on AWS. Specialized in migrating legacy workloads to serverless architectures to reduce TCO.',
    skills: ['AWS Architecture', 'Serverless', 'Migration', 'CloudFormation', 'API Design', 'NoSQL', 'Event-Driven', 'FinOps'],
    tools: ['AWS Lambda', 'DynamoDB', 'API Gateway', 'CDK', 'EventBridge', 'CloudFront', 'Cognito', 'Step Functions'],
    demandLevel: 'Very High',
    marketScore: 96,
    yearsExperience: 10
  },
  {
    id: '10',
    firstName: 'Sophie',
    lastInitial: 'A',
    title: 'Cloud Data Engineer',
    location: 'Wellington',
    status: '4 Weeks',
    summary: 'Data infrastructure specialist building scalable data lakes and ETL pipelines for government analytics. Expert in securing sensitive data in transit and at rest.',
    skills: ['Data Engineering', 'ETL/ELT', 'Data Warehousing', 'Python', 'Big Data', 'Data Governance', 'SQL', 'Stream Processing'],
    tools: ['Snowflake', 'AWS Glue', 'Redshift', 'Airflow', 'Spark', 'Kinesis', 'dbt', 'Terraform'],
    demandLevel: 'High',
    marketScore: 92,
    yearsExperience: 6
  },
  {
    id: '11',
    firstName: 'Daniel',
    lastInitial: 'C',
    title: 'AWS DevOps Engineer',
    location: 'Christchurch',
    status: 'Immediate',
    summary: 'Automating infrastructure provisioning and application deployment using modern CI/CD practices. Focused on reducing deployment frequency from weeks to hours.',
    skills: ['AWS DevOps', 'CI/CD', 'Infrastructure as Code', 'Scripting', 'Container Orchestration', 'Monitoring', 'Linux', 'Security Automation'],
    tools: ['CodePipeline', 'CloudFormation', 'ECS', 'Docker', 'Bash', 'Python', 'SonarQube', 'SSM'],
    demandLevel: 'High',
    marketScore: 89,
    yearsExperience: 5
  },
  {
    id: '12',
    firstName: 'Priya',
    lastInitial: 'N',
    title: 'Full Stack Cloud Developer',
    location: 'Auckland',
    status: '2 Weeks',
    summary: 'Hybrid developer/engineer capable of building the platform and the application. Deep expertise in React frontends backed by scalable AWS microservices.',
    skills: ['Full Stack', 'Microservices', 'Node.js', 'React', 'API Development', 'AWS', 'Database Design', 'Testing'],
    tools: ['TypeScript', 'Next.js', 'AWS Amplify', 'RDS', 'Elasticsearch', 'GraphQL', 'Jest', 'Cypress'],
    demandLevel: 'Medium',
    marketScore: 85,
    yearsExperience: 7
  },
  {
    id: '13',
    firstName: 'Marcus',
    lastInitial: 'E',
    title: 'Platform Engineer (AWS/K8s)',
    location: 'Wellington',
    status: 'Immediate',
    summary: 'Building internal developer platforms (IDP) to streamline engineering workflows. Expert in EKS cluster management and service mesh implementation.',
    skills: ['Kubernetes', 'Platform Engineering', 'Developer Experience', 'Service Mesh', 'Networking', 'GitOps', 'Observability', 'Golang'],
    tools: ['EKS', 'Backstage', 'FluxCD', 'Linkerd', 'ExternalDNS', 'Cert-Manager', 'OIDC', 'Velero'],
    demandLevel: 'Critical',
    marketScore: 94,
    yearsExperience: 8
  },
  {
    id: '14',
    firstName: 'Olivia',
    lastInitial: 'G',
    title: 'Cloud Security Specialist',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'DevSecOps engineer focused on shifting security left in the development lifecycle. Implementing automated compliance checks and vulnerability scanning.',
    skills: ['Cloud Security', 'DevSecOps', 'Compliance', 'IAM', 'Vulnerability Mgmt', 'Container Security', 'Encryption', 'Audit'],
    tools: ['AWS Security Hub', 'GuardDuty', 'Snyk', 'Checkov', 'Wiz', 'Trivy', 'KMS', 'WAF'],
    demandLevel: 'Very High',
    marketScore: 93,
    yearsExperience: 9
  },
  // GCP & Multi-Cloud
  {
    id: '15',
    firstName: 'Wei',
    lastInitial: 'Z',
    title: 'GCP Data Architect',
    location: 'Auckland',
    status: '4 Weeks',
    summary: 'Designing high-throughput data processing systems on Google Cloud. Specialist in BigQuery optimization and real-time analytics dashboards.',
    skills: ['GCP Architecture', 'Big Data', 'Machine Learning Ops', 'Data Strategy', 'Real-time Analytics', 'Java', 'Python', 'Pub/Sub'],
    tools: ['BigQuery', 'Dataflow', 'Cloud Run', 'Looker', 'Vertex AI', 'Cloud Spanner', 'Composer', 'GKE'],
    demandLevel: 'High',
    marketScore: 91,
    yearsExperience: 11
  },
  {
    id: '16',
    firstName: 'Thomas',
    lastInitial: 'R',
    title: 'SRE & Multi-Cloud Engineer',
    location: 'Dunedin',
    status: 'Immediate',
    summary: 'Infrastructure generalist comfortable managing workloads across AWS, Azure, and GCP. Expert in unifying observability and incident response processes.',
    skills: ['Multi-Cloud', 'SRE', 'Incident Response', 'Automation', 'Networking', 'Linux', 'Terraform', 'Scripting'],
    tools: ['GCP Operations', 'Stackdriver', 'PagerDuty', 'Ansible', 'HashiCorp Vault', 'Consul', 'Packer', 'Ubuntu'],
    demandLevel: 'High',
    marketScore: 88,
    yearsExperience: 12
  },
  {
    id: '17',
    firstName: 'Elena',
    lastInitial: 'V',
    title: 'GCP Cloud Engineer',
    location: 'Wellington',
    status: '2 Weeks',
    summary: 'Specialized in containerizing legacy applications and moving them to Google Kubernetes Engine (GKE). Strong focus on stateless application design.',
    skills: ['GCP', 'Kubernetes', 'Docker', 'Migration', 'Networking', 'Storage', 'IAM', 'Troubleshooting'],
    tools: ['GKE', 'Cloud Build', 'Artifact Registry', 'Cloud SQL', 'VPC', 'Cloud Armor', 'Anthos', 'Bash'],
    demandLevel: 'Medium',
    marketScore: 86,
    yearsExperience: 6
  },
  // Azure & Microsoft Stack
  {
    id: '18',
    firstName: 'Chris',
    lastInitial: 'J',
    title: 'Azure Integration Specialist',
    location: 'Hamilton',
    status: 'Immediate',
    summary: 'Backend integration expert connecting enterprise ERPs with modern cloud services. Deep knowledge of API management and asynchronous messaging patterns.',
    skills: ['Azure Integration', 'API Management', 'Messaging', 'Serverless', '.NET Core', 'SQL', 'Enterprise Arch', 'Hybrid Cloud'],
    tools: ['Logic Apps', 'Service Bus', 'API Management', 'Event Grid', 'Azure Functions', 'Cosmos DB', 'C#', 'SQL Server'],
    demandLevel: 'Medium',
    marketScore: 87,
    yearsExperience: 13
  },
  {
    id: '19',
    firstName: 'Natalie',
    lastInitial: 'K',
    title: 'Microsoft 365 Security Lead',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Securing the modern workplace with advanced threat protection and identity governance. Helping organisations achieve zero-trust maturity.',
    skills: ['M365 Security', 'Identity Governance', 'Information Protection', 'Compliance', 'Email Security', 'Device Mgmt', 'Zero Trust', 'Auditing'],
    tools: ['Defender for 365', 'Purview', 'Entra ID P2', 'Sentinel', 'Intune', 'Conditional Access', 'eDiscovery', 'Powershell'],
    demandLevel: 'Very High',
    marketScore: 92,
    yearsExperience: 10
  },
  {
    id: '20',
    firstName: 'Ryan',
    lastInitial: 'D',
    title: 'Azure Virtual Desktop Engineer',
    location: 'Christchurch',
    status: 'Immediate',
    summary: 'VDI specialist designing and managing large-scale Azure Virtual Desktop environments. Focused on user experience optimization and cost management.',
    skills: ['VDI', 'Azure Virtual Desktop', 'Image Management', 'Performance Tuning', 'Networking', 'Storage', 'Automation', 'Citrix'],
    tools: ['AVD', 'FSLogix', 'Nerdio', 'Azure Monitor', 'PowerShell', 'Windows 11', 'RemoteApp', 'Azure NetApp Files'],
    demandLevel: 'High',
    marketScore: 89,
    yearsExperience: 8
  },
  {
    id: '21',
    firstName: 'Jessica',
    lastInitial: 'T',
    title: 'Power Platform Developer',
    location: 'Auckland',
    status: '2 Weeks',
    summary: 'Automating business processes and building low-code solutions to replace legacy spreadsheets. Integrating Power Apps with Dataverse and Azure SQL.',
    skills: ['Low Code', 'Process Automation', 'App Development', 'Data Modeling', 'Integration', 'Governance', 'Reporting', 'UI/UX'],
    tools: ['Power Apps', 'Power Automate', 'Power BI', 'Dataverse', 'SharePoint', 'Teams', 'CoPilot Studio', 'SQL'],
    demandLevel: 'Medium',
    marketScore: 84,
    yearsExperience: 5
  },
  {
    id: '22',
    firstName: 'Andrew',
    lastInitial: 'M',
    title: 'Senior .NET Cloud Developer',
    location: 'Wellington',
    status: '4 Weeks',
    summary: 'Re-platforming monolithic .NET applications to Azure App Service and Container Apps. Expert in modernization strategies and database migration.',
    skills: ['.NET', 'Azure PaaS', 'Application Modernization', 'Database Design', 'Microservices', 'DevOps', 'Caching', 'Search'],
    tools: ['C#', 'ASP.NET Core', 'Azure App Service', 'SQL Azure', 'Redis', 'Azure DevOps', 'Application Insights', 'Key Vault'],
    demandLevel: 'High',
    marketScore: 90,
    yearsExperience: 12
  },
  // Networking & Infrastructure
  {
    id: '23',
    firstName: 'Kevin',
    lastInitial: 'L',
    title: 'Senior Network Engineer',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'CCIE-level network engineer handling complex routing and switching for data center environments. Experienced in transitioning to software-defined networking.',
    skills: ['Network Engineering', 'Routing/Switching', 'Data Center', 'SDN', 'Firewalls', 'Load Balancing', 'Troubleshooting', 'Design'],
    tools: ['Cisco NX-OS', 'Juniper', 'BGP', 'OSPF', 'ACI', 'F5 BIG-IP', 'Wireshark', 'Python'],
    demandLevel: 'High',
    marketScore: 91,
    yearsExperience: 15
  },
  {
    id: '24',
    firstName: 'Lisa',
    lastInitial: 'P',
    title: 'Wireless Network Specialist',
    location: 'Hamilton',
    status: 'Immediate',
    summary: 'Designing high-density wireless networks for campus and warehouse environments. Expert in site surveys, RF analysis, and security implementation.',
    skills: ['Wireless Networking', 'RF Analysis', 'Network Design', 'Security', 'NAC', 'Troubleshooting', 'IoT', 'Project Mgmt'],
    tools: ['Ekahau', 'Cisco Meraki', 'Aruba', 'ISE', '802.1x', 'WLC', 'Splunk', 'Visio'],
    demandLevel: 'Medium',
    marketScore: 86,
    yearsExperience: 9
  },
  {
    id: '25',
    firstName: 'Mark',
    lastInitial: 'S',
    title: 'Infrastructure Automation Engineer',
    location: 'Wellington',
    status: '2 Weeks',
    summary: 'Replacing manual server builds with Ansible playbooks and Terraform. Focused on immutable infrastructure patterns for on-premise VMware environments.',
    skills: ['Automation', 'Virtualization', 'Scripting', 'Config Management', 'Linux', 'Windows Server', 'Storage', 'Networking'],
    tools: ['Ansible', 'Terraform', 'VMware vSphere', 'PowerShell', 'Python', 'Git', 'Jenkins', 'Pure Storage'],
    demandLevel: 'High',
    marketScore: 89,
    yearsExperience: 7
  },
  // Security & Cyber
  {
    id: '26',
    firstName: 'Rachel',
    lastInitial: 'H',
    title: 'Penetration Tester / Ethical Hacker',
    location: 'Auckland',
    status: '4 Weeks',
    summary: 'Offensive security specialist conducting web application and infrastructure assessments. Helping teams identify and remediate critical vulnerabilities before exploitation.',
    skills: ['Penetration Testing', 'Vulnerability Assessment', 'Web Security', 'Network Security', 'Reporting', 'Scripting', 'Social Engineering', 'Exploitation'],
    tools: ['Burp Suite', 'Metasploit', 'Nmap', 'Cobalt Strike', 'Python', 'OWASP Top 10', 'Nessus', 'Linux'],
    demandLevel: 'High',
    marketScore: 94,
    yearsExperience: 6
  },
  {
    id: '27',
    firstName: 'Justin',
    lastInitial: 'B',
    title: 'SOC Analyst L3',
    location: 'Wellington',
    status: 'Immediate',
    summary: 'Senior analyst leading threat hunting initiatives and managing critical security incidents. Developing detection rules to catch advanced persistent threats.',
    skills: ['Threat Analysis', 'Incident Response', 'Forensics', 'SIEM Tuning', 'Malware Analysis', 'Log Analysis', 'Reporting', 'Mentoring'],
    tools: ['Splunk ES', 'Sentinel', 'ELK Stack', 'Wireshark', 'EnCase', 'MITRE ATT&CK', 'VirusTotal', 'Python'],
    demandLevel: 'High',
    marketScore: 88,
    yearsExperience: 8
  },
  {
    id: '28',
    firstName: 'Hannah',
    lastInitial: 'C',
    title: 'Identity & Access Management Architect',
    location: 'Auckland',
    status: '2 Weeks',
    summary: 'Designing comprehensive IAM solutions for large enterprise environments. Integrating HR systems with directory services for automated lifecycle management.',
    skills: ['IAM', 'IGA', 'PAM', 'SSO', 'Directory Services', 'Security Architecture', 'Compliance', 'Federation'],
    tools: ['SailPoint', 'CyberArk', 'Okta', 'Active Directory', 'Entra ID', 'PingIdentity', 'SAML', 'OIDC'],
    demandLevel: 'Very High',
    marketScore: 95,
    yearsExperience: 14
  },
  // Data & AI Infrastructure
  {
    id: '29',
    firstName: 'Alex',
    lastInitial: 'W',
    title: 'AI Infrastructure Engineer',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Building and maintaining the GPU clusters and pipelines required for LLM training and inference. Optimizing hardware utilization and model serving latency.',
    skills: ['AI/ML Ops', 'GPU Computing', 'Model Serving', 'Kubernetes', 'Python', 'Performance Tuning', 'Storage', 'Networking'],
    tools: ['NVIDIA CUDA', 'Ray', 'Kubeflow', 'PyTorch', 'Hugging Face', 'Docker', 'Prometheus', 'Linux'],
    demandLevel: 'Critical',
    marketScore: 98,
    yearsExperience: 5
  },
  {
    id: '30',
    firstName: 'Grace',
    lastInitial: 'L',
    title: 'Database Reliability Engineer',
    location: 'Christchurch',
    status: '2 Weeks',
    summary: 'Specialist in high-availability database architectures. managing large PostgreSQL fleets and tuning query performance for sub-millisecond response times.',
    skills: ['Database Admin', 'Performance Tuning', 'High Availability', 'Disaster Recovery', 'Automation', 'SQL', 'NoSQL', 'Cloud DBs'],
    tools: ['PostgreSQL', 'Patroni', 'PgBouncer', 'Ansible', 'Linux', 'Datadog', 'Oracle', 'MongoDB'],
    demandLevel: 'High',
    marketScore: 92,
    yearsExperience: 11
  },
  // DevOps & Tooling
  {
    id: '31',
    firstName: 'Ben',
    lastInitial: 'K',
    title: 'Build & Release Engineer',
    location: 'Wellington',
    status: 'Immediate',
    summary: 'Expert in software supply chain security and reproducible builds. Managing artifact repositories and dependency scanning for large dev teams.',
    skills: ['Release Mgmt', 'Build Systems', 'Security', 'Scripting', 'Version Control', 'Packaging', 'Compliance', 'DevOps'],
    tools: ['Artifactory', 'Jenkins', 'Gradle', 'Maven', 'Git', 'Snyk', 'Docker', 'Bash'],
    demandLevel: 'Medium',
    marketScore: 85,
    yearsExperience: 8
  },
  {
    id: '32',
    firstName: 'Chloe',
    lastInitial: 'M',
    title: 'Linux Systems Administrator',
    location: 'Dunedin',
    status: 'Immediate',
    summary: 'Deep kernel-level Linux expertise for performance critical applications. Managing large fleets of RHEL servers including patching and compliance.',
    skills: ['Linux Admin', 'Shell Scripting', 'Networking', 'Storage', 'Security', 'Performance Tuning', 'Virtualization', 'Config Mgmt'],
    tools: ['RHEL', 'Ubuntu', 'Satellite', 'Ansible', 'SELinux', 'LVM', 'Systemd', 'Nagios'],
    demandLevel: 'Medium',
    marketScore: 84,
    yearsExperience: 15
  },
  // More Cloud & Generalists
  {
    id: '33',
    firstName: 'Tim',
    lastInitial: 'R',
    title: 'Cloud Migration Lead',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Leading technical teams through complex datacenter exits. Expert in lift-and-shift as well as refactoring strategies for legacy applications.',
    skills: ['Migration', 'Project Leadership', 'AWS', 'Azure', 'Stakeholder Mgmt', 'Hybrid Cloud', 'Networking', 'Storage'],
    tools: ['Azure Migrate', 'AWS MGN', 'Carbonite', 'VMware', 'Excel', 'Jira', 'Visio', 'PowerShell'],
    demandLevel: 'High',
    marketScore: 90,
    yearsExperience: 16
  },
  {
    id: '34',
    firstName: 'Nicole',
    lastInitial: 'S',
    title: 'Junior DevOps Engineer',
    location: 'Wellington',
    status: 'Immediate',
    summary: 'Energetic junior engineer with strong Python skills and a passion for automation. Quickly learning cloud patterns and assisting with pipeline maintenance.',
    skills: ['DevOps', 'Python', 'Scripting', 'Cloud Basics', 'Git', 'Learning Agility', 'Linux', 'Troubleshooting'],
    tools: ['GitLab CI', 'AWS', 'Docker', 'Bash', 'Jira', 'Confluence', 'VS Code', 'Slack'],
    demandLevel: 'Medium',
    marketScore: 80,
    yearsExperience: 2
  },
  {
    id: '35',
    firstName: 'Paul',
    lastInitial: 'T',
    title: 'Enterprise Architect (Infrastructure)',
    location: 'Auckland',
    status: '4 Weeks',
    summary: 'Strategic advisor for C-level executives on technology roadmaps. Translating business goals into scalable and secure infrastructure designs.',
    skills: ['Enterprise Arch', 'Strategy', 'Governance', 'Cloud', 'Security', 'Digital Transformation', 'Budgeting', 'Communication'],
    tools: ['TOGAF', 'ArchiMate', 'Sparx EA', 'PowerPoint', 'Azure', 'AWS', 'Hybrid Cloud', 'Roadmapping'],
    demandLevel: 'Very High',
    marketScore: 93,
    yearsExperience: 20
  },
  {
    id: '36',
    firstName: 'Emily',
    lastInitial: 'W',
    title: 'ServiceNow Platform Developer',
    location: 'Wellington',
    status: '2 Weeks',
    summary: 'Customizing ServiceNow ITSM and ITOM modules to streamline IT operations. Integrating ServiceNow with monitoring and deployment tools.',
    skills: ['ITSM', 'ITOM', 'JavaScript', 'Integration', 'Workflow Design', 'CMDB', 'Portal Dev', 'Business Analysis'],
    tools: ['ServiceNow', 'JavaScript', 'REST API', 'Flow Designer', 'Service Portal', 'MID Server', 'HTML/CSS', 'Angular'],
    demandLevel: 'High',
    marketScore: 91,
    yearsExperience: 6
  },
  {
    id: '37',
    firstName: 'Adam',
    lastInitial: 'F',
    title: 'VoIP & Unified Comms Engineer',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Specialist in Teams Calling and legacy PBX migrations. Ensuring high voice quality and reliability for contact centers.',
    skills: ['VoIP', 'SIP', 'Teams Calling', 'Contact Center', 'Networking', 'SBC', 'Troubleshooting', 'Migration'],
    tools: ['Microsoft Teams', 'AudioCodes', 'Ribbon', 'Wireshark', 'Anywhere365', 'Genesys', 'PowerShell', 'QoS'],
    demandLevel: 'Medium',
    marketScore: 86,
    yearsExperience: 12
  },
  {
    id: '38',
    firstName: 'Rebecca',
    lastInitial: 'N',
    title: 'Storage & Backup Engineer',
    location: 'Christchurch',
    status: 'Immediate',
    summary: 'Managing petabyte-scale storage arrays and ensuring 100% data recoverability. Specialist in ransomware protection for backup repositories.',
    skills: ['Storage Area Networks', 'Backup & Recovery', 'Disaster Recovery', 'Ransomware Protection', 'Cloud Storage', 'Capacity Planning', 'Linux', 'Virtualization'],
    tools: ['NetApp', 'Pure Storage', 'Veeam', 'Commvault', 'Rubrik', 'Brocade', 'AWS S3', 'Azure Blob'],
    demandLevel: 'Medium',
    marketScore: 87,
    yearsExperience: 10
  },
  {
    id: '39',
    firstName: 'Ian',
    lastInitial: 'G',
    title: 'Citrix & VDI Architect',
    location: 'Hamilton',
    status: '2 Weeks',
    summary: 'Designing complex remote access solutions for secure environments. Expert in application virtualization and optimizing protocol performance over WAN.',
    skills: ['Citrix', 'VDI', 'Virtualization', 'Networking', 'Security', 'User Experience', 'Load Balancing', 'Troubleshooting'],
    tools: ['Citrix CVAD', 'NetScaler', 'VMware Horizon', 'IGEL', 'ControlUp', 'PowerShell', 'Windows Server', 'FSLogix'],
    demandLevel: 'Medium',
    marketScore: 89,
    yearsExperience: 14
  },
  {
    id: '40',
    firstName: 'Julie',
    lastInitial: 'D',
    title: 'Scrum Master / Agile Delivery Lead',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Technical delivery lead helping infrastructure squads adopt Agile practices. Removing blockers and improving velocity for cloud migration teams.',
    skills: ['Agile', 'Scrum', 'Kanban', 'Coaching', 'Facilitation', 'Project Mgmt', 'Jira', 'DevOps Culture'],
    tools: ['Jira', 'Confluence', 'Azure DevOps', 'Miro', 'Trello', 'Slack', 'Teams', 'Excel'],
    demandLevel: 'Medium',
    marketScore: 83,
    yearsExperience: 8
  },
  {
    id: '41',
    firstName: 'Ross',
    lastInitial: 'H',
    title: 'Splunk Engineer',
    location: 'Wellington',
    status: 'Immediate',
    summary: 'Building and maintaining large-scale Splunk clusters for security and observability. Creating custom apps and dashboards for executive reporting.',
    skills: ['Splunk Admin', 'Data Ingestion', 'Search & Reporting', 'Dashboarding', 'Regex', 'Linux', 'Security', 'Automation'],
    tools: ['Splunk Enterprise', 'Splunk Cloud', 'ITSI', 'Cribl', 'Python', 'Linux', 'Ansible', 'Git'],
    demandLevel: 'High',
    marketScore: 88,
    yearsExperience: 5
  },
  {
    id: '42',
    firstName: 'Michelle',
    lastInitial: 'B',
    title: 'MacOS Endpoint Engineer',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Managing Apple device fleets in enterprise environments. Integrating Macs with Active Directory and ensuring zero-touch provisioning.',
    skills: ['MacOS Management', 'MDM', 'Scripting', 'Security', 'Identity', 'Packaging', 'Support', 'Networking'],
    tools: ['Jamf Pro', 'Intune', 'Bash', 'Swift', 'Apple Business Mgr', 'Munki', 'Nomad', 'Wireshark'],
    demandLevel: 'Low',
    marketScore: 82,
    yearsExperience: 7
  },
  {
    id: '43',
    firstName: 'Nathan',
    lastInitial: 'K',
    title: 'Senior Network Automation Engineer',
    location: 'Auckland',
    status: '2 Weeks',
    summary: 'Transitioning network operations from CLI to API-driven automation. Building self-service portals for firewall rule requests and switch provisioning.',
    skills: ['Network Automation', 'Python', 'API', 'SDN', 'CI/CD', 'Routing', 'Linux', 'Web Dev'],
    tools: ['Ansible', 'Python', 'Nornir', 'Django', 'GitLab', 'Arista', 'Cisco DNA', 'RestConf'],
    demandLevel: 'Very High',
    marketScore: 94,
    yearsExperience: 9
  },
  {
    id: '44',
    firstName: 'Laura',
    lastInitial: 'M',
    title: 'Dynamics 365 Technical Consultant',
    location: 'Christchurch',
    status: '4 Weeks',
    summary: 'Customizing and extending Dynamics 365 CRM for sales and customer service teams. Integrating with the wider Power Platform ecosystem.',
    skills: ['Dynamics 365', 'CRM', 'Customization', 'Integration', 'C#', 'JavaScript', 'Solution Architecture', 'Data Migration'],
    tools: ['Dynamics 365', 'Power Automate', 'Azure', 'Plugin Registration', 'XrmToolBox', 'FetchXML', 'SSIS', 'KingswaySoft'],
    demandLevel: 'Medium',
    marketScore: 88,
    yearsExperience: 6
  },
  {
    id: '45',
    firstName: 'Steve',
    lastInitial: 'P',
    title: 'Kafka Streaming Engineer',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Event streaming specialist managing mission-critical Kafka clusters. Ensuring data integrity and low latency for financial transaction processing.',
    skills: ['Event Streaming', 'Distributed Systems', 'Java', 'Ops', 'Monitoring', 'Security', 'Performance', 'Architecture'],
    tools: ['Apache Kafka', 'Confluent', 'ZooKeeper', 'Schema Registry', 'Kafka Connect', 'KSQL', 'Prometheus', 'Grafana'],
    demandLevel: 'High',
    marketScore: 93,
    yearsExperience: 8
  },
  {
    id: '46',
    firstName: 'Amy',
    lastInitial: 'R',
    title: 'QA Automation Lead',
    location: 'Wellington',
    status: 'Immediate',
    summary: 'Building robust test automation frameworks for web and API applications. Mentoring manual testers to transition into automation engineering roles.',
    skills: ['Test Automation', 'QA Strategy', 'CI/CD', 'Coding', 'API Testing', 'Performance Testing', 'Agile', 'Mentoring'],
    tools: ['Selenium', 'Playwright', 'TypeScript', 'Postman', 'JMeter', 'Azure DevOps', 'SpecFlow', 'C#'],
    demandLevel: 'Medium',
    marketScore: 86,
    yearsExperience: 10
  },
  {
    id: '47',
    firstName: 'Eric',
    lastInitial: 'J',
    title: 'Blockchain / Web3 Infrastructure Eng',
    location: 'Auckland',
    status: 'Immediate',
    summary: 'Managing validator nodes and infrastructure for blockchain networks. Deep understanding of cryptographic security and decentralized consensus mechanisms.',
    skills: ['Blockchain', 'Node Ops', 'Security', 'Cryptography', 'Linux', 'Cloud', 'Networking', 'Monitoring'],
    tools: ['Ethereum', 'Solana', 'Docker', 'AWS', 'Rust', 'Go', 'Geth', 'Grafana'],
    demandLevel: 'Low',
    marketScore: 85,
    yearsExperience: 4
  },
  {
    id: '48',
    firstName: 'Zoe',
    lastInitial: 'L',
    title: 'Technical Writer / Documentation Specialist',
    location: 'Remote',
    status: 'Immediate',
    summary: 'Creating clear, concise technical documentation for complex infrastructure systems. Helping engineering teams maintain high-quality runbooks and API docs.',
    skills: ['Technical Writing', 'Documentation', 'Diagramming', 'API Docs', 'Markdown', 'Communication', 'Editing', 'Process Mapping'],
    tools: ['Confluence', 'GitBook', 'Swagger', 'Visio', 'Lucidchart', 'Markdown', 'Jira', 'SharePoint'],
    demandLevel: 'Low',
    marketScore: 80,
    yearsExperience: 12
  }
];